feat(input): [NoTicket] Extend input
getPopsure/dirty-swan pull request #157
Opened 2022-12-20 09:25 UTC by busypeoples

### What this PR does

* Add a new placeholderAsLabel property to the Input component
* If the flag is set to false, the placeholder will not transform into a label

![input-placeholder](https://user-images.githubusercontent.com/718727/208631599-cbd4ff42-7e8b-49a8-860b-b101ad47ac4f.png)

### Checklist:

- [ ] I reviewed my own code
- [ ] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [ ] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [ ] I have updated the task(s) status on Linear
- [ ] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

2022-12-20 13:20 UTC, talo242 requested changes

2022-12-20 14:28 UTC, busypeoples commented on src/lib/components/input/index.tsx
> +      placeholderAsLabel = true,
Agreed regarding `label` being needed for accessibility.

2022-12-21 09:12 UTC, busypeoples commented on src/lib/components/input/index.tsx
> +      placeholderAsLabel = true,
@talo242 this makes a lot of sense. What is the best way forward here? Should we add the `label` property and make it backwards compatible ensuring that the current way this component works doesn't change if no `label` is provided?

2022-12-22 08:06 UTC, kimkwanka commented on src/lib/components/input/index.tsx
> +      placeholderAsLabel = true,
Another related problem is that the actual `placeholder` attribute on the `input` is set to `" "` which makes it "untargetable" via React Testing Library for example. This however, does not actually affect `a11y` as screen readers [don't seem to read the placeholder](https://github.com/microsoft/fluentui/issues/16583#issuecomment-767164317).

2023-01-16 14:46 UTC, busypeoples commented on src/lib/components/input/index.tsx
> +      placeholderAsLabel = true,
With the current implementation if you provide a `label`, the input will use the actual `placeholder`. In the future we should make the `label` required.

2023-01-16 14:47 UTC, talo242 approved these changes
Looking good! ✨

2023-01-16 16:46 UTC, ruizhen88 approved these changes

2023-01-17 08:47 UTC, kimkwanka approved these changes

2023-01-18 10:51 UTC, merged