fix(comparison-table): Fix comparisonTable maxWidth on mobile
getPopsure/dirty-swan pull request #221
Opened 2023-05-24 17:33 UTC by diogomateus

### What this PR does
Fix comparisonTable maxWidth on mobile, which doesn't trigger on mobile devices. This seems to be only visible on website, not on storybook.

### How to test?
`Spotted this issue on public LP on mobile. The name appears after scrolling horizontally a bit `
![File](https://github.com/getPopsure/dirty-swan/assets/4015038/9386e824-f818-47d0-bc1f-8f0656105fa3)

### Checklist:

- [x] I reviewed my own code
- [x] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [x] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [ ] I have updated the task(s) status on Linear
- [ ] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

2023-05-25 05:54 UTC, kimkwanka requested changes
Isn't this the exact change that was [done here](https://github.com/getPopsure/dirty-swan/pull/186/files) and then [got reverted](https://github.com/getPopsure/dirty-swan/pull/202) because it borked something else?

2023-05-25 11:16 UTC, diogomateus commented
> Isn't this the exact change that was [done here](https://github.com/getPopsure/dirty-swan/pull/186/files) and then [got reverted](https://github.com/getPopsure/dirty-swan/pull/202) because it borked something else?

I didn't know about this change from @busypeoples, only that this was changed to try to fix the table flaky styles.
@busypeoples do you remember this fix and what it was breaking?

2023-05-30 07:48 UTC, busypeoples commented
> > Isn't this the exact change that was [done here](https://github.com/getPopsure/dirty-swan/pull/186/files) and then [got reverted](https://github.com/getPopsure/dirty-swan/pull/202) because it borked something else?
> 
> I didn't know about this change from @busypeoples, only that this was changed to try to fix the table flaky styles. @busypeoples do you remember this fix and what it was breaking?

@diogomateus Can't recall in detail why the change wasn't working, but from what I recall is that the comparison table looked broken on mobile.

2023-05-30 09:15 UTC, diogomateus commented
@kimkwanka @busypeoples 

A bit of context to understand this update.

1. The current state is that on mobile we have an issue where we need to swipe to get the correct header values as Andrey reporterd:
<img width="300" alt="Screenshot 2023-05-30 at 10 11 58" src="https://github.com/getPopsure/dirty-swan/assets/4015038/a48dd52e-722f-4c47-9911-5f53ad6b4fd7">

2. The revert that Ali did was to fix this issue with aligning no tabled and slightly on mobile:
<img width="300" alt="Screenshot 2023-05-30 at 10 10 52" src="https://github.com/getPopsure/dirty-swan/assets/4015038/0dbe4c97-6874-4a73-88c3-51b38aeff021">
<img width="300" alt="Screenshot 2023-05-30 at 10 10 47" src="https://github.com/getPopsure/dirty-swan/assets/4015038/635e5812-89e0-41ef-8367-495c432d1856">

3. I tested this linking with `website` and my solution is to use 100vw but only on mobile as when it's on mobile the header is full width (there's already a 16px padding). This ensures that the only thing changing is the mobile, as everything else seems to be working as expected.
<img width="300" alt="Screenshot 2023-05-30 at 10 10 29" src="https://github.com/getPopsure/dirty-swan/assets/4015038/72ba9f86-016f-4947-9463-6ffeccc523da">

2023-05-31 08:10 UTC, kimkwanka approved these changes

2023-05-31 08:22 UTC, merged