fix(CoverageTable): [EPIC-137] Fix details toggle messing up refs
getPopsure/dirty-swan pull request #318
Opened 2024-06-10 10:07 UTC by kimkwanka

### What this PR does

This PR fixes an issue when toggling details on then off, where the scrollContainerRef would get lost.

This is accomplished by 2 things:
1. Using the new prop "InnerRef" that [can finally be used to get the ref to the child component again](https://github.com/okonet/react-scroll-sync/pull/90) inside a `ScrollSyncPane`. This way a consistent ref is retained.
2. Removing the "disabled" state from TableArrows as it was somehow messing with the refs for some unknown reason.

Before:

https://github.com/getPopsure/dirty-swan/assets/13664983/eedcc601-1a37-4141-8185-908210c4fddc

After:

https://github.com/getPopsure/dirty-swan/assets/13664983/2689eb5e-8d0a-4e89-9b92-fe57a47981eb

### How to test?

On a mobile view, navigate to the very last item, then toggle details on, then off. Try to navigate the items again. It should work again,

### Checklist:

- [x] I reviewed my own code
- [x] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [x] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [x] I have updated the task(s) status on Linear
- [x] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Edge

2024-06-10 15:48 UTC, diogomateus requested changes
The navigation arrows on mobile stopped working, can you take a look?
<img width="411" alt="Screenshot 2024-06-10 at 16 47 10" src="https://github.com/getPopsure/dirty-swan/assets/4015038/f9cbb08f-6996-4460-a807-d8c17ee738ba">

2024-06-11 08:09 UTC, kimkwanka commented
> The navigation arrows on mobile stopped working, can you take a look? <img alt="Screenshot 2024-06-10 at 16 47 10" width="411" src="https://private-user-images.githubusercontent.com/4015038/338255576-f9cbb08f-6996-4460-a807-d8c17ee738ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTM0NzgsIm5iZiI6MTcxODA5MzE3OCwicGF0aCI6Ii80MDE1MDM4LzMzODI1NTU3Ni1mOWNiYjA4Zi02OTk2LTQ0NjAtYTgwNy1kOGMxN2VlNzM4YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDgwNjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTljMDhlOTk0YTliMDA2N2IzYjhkZDk3NzBlNmQyNjBiZDQyMWEwYjRhMTkwYzJiNjYxZDUxNGE2MmQ1ODIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SA88qhe9rK0-4S5nG4W5YXTCXhfPaAPvRZH224RR6i0">

Can you provide more context? I can't seem to reproduce this @diogomateus

2024-06-11 08:17 UTC, diogomateus commented
> > The navigation arrows on mobile stopped working, can you take a look? <img alt="Screenshot 2024-06-10 at 16 47 10" width="411" src="https://private-user-images.githubusercontent.com/4015038/338255576-f9cbb08f-6996-4460-a807-d8c17ee738ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTM0NzgsIm5iZiI6MTcxODA5MzE3OCwicGF0aCI6Ii80MDE1MDM4LzMzODI1NTU3Ni1mOWNiYjA4Zi02OTk2LTQ0NjAtYTgwNy1kOGMxN2VlNzM4YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDgwNjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTljMDhlOTk0YTliMDA2N2IzYjhkZDk3NzBlNmQyNjBiZDQyMWEwYjRhMTkwYzJiNjYxZDUxNGE2MmQ1ODIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SA88qhe9rK0-4S5nG4W5YXTCXhfPaAPvRZH224RR6i0">
> 
> Can you provide more context? I can't seem to reproduce this @diogomateus

Keeps happening to me when moving to the mobile version, the arrows don't work anymore (but syncing scroll position does)
https://github.com/getPopsure/dirty-swan/assets/4015038/c1729106-07f1-4946-9c46-c492ded7f665

2024-06-12 07:31 UTC, kimkwanka commented
> > > The navigation arrows on mobile stopped working, can you take a look? <img alt="Screenshot 2024-06-10 at 16 47 10" width="411" src="https://private-user-images.githubusercontent.com/4015038/338255576-f9cbb08f-6996-4460-a807-d8c17ee738ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTM0NzgsIm5iZiI6MTcxODA5MzE3OCwicGF0aCI6Ii80MDE1MDM4LzMzODI1NTU3Ni1mOWNiYjA4Zi02OTk2LTQ0NjAtYTgwNy1kOGMxN2VlNzM4YmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDgwNjE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTljMDhlOTk0YTliMDA2N2IzYjhkZDk3NzBlNmQyNjBiZDQyMWEwYjRhMTkwYzJiNjYxZDUxNGE2MmQ1ODIyNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SA88qhe9rK0-4S5nG4W5YXTCXhfPaAPvRZH224RR6i0">
> > 
> > 
> > Can you provide more context? I can't seem to reproduce this @diogomateus
> 
> Keeps happening to me when moving to the mobile version, the arrows don't work anymore (but syncing scroll position does) https://github.com/getPopsure/dirty-swan/assets/4015038/c1729106-07f1-4946-9c46-c492ded7f665

Still can't reproduce, not sure what's happening here. Can you check with a freshly cloned dirty-swan copy? I did just that just to make sure I don't have any weird stuff in node_modules, and it works just fine for me. 😕

2024-06-12 08:09 UTC, diogomateus approved these changes

2024-06-12 08:09 UTC, merged