refactor(modal): Refactor Modal and add modal footer
getPopsure/dirty-swan pull request #329
Opened 2024-06-20 11:41 UTC by diogomateus

### What this PR does
Refactors and cleans 

### Why is this needed?

Please include relevant motivation and context of why this PR is necessary, sentry/linear/notion/...

Solves:
STO-XXX
EMU-XXX
RVN-XXX

### How to test?

_Please include additional context on how to test this PR._

### Checklist:

- [ ] I reviewed my own code
- [ ] The changes align with the designs I received  
  Or give a reason why this does not apply:
- [ ] I have attached screenshot(s), video(s) or gif(s) showing that the solution is working as expected  
  Or give a reason why this does not apply:
- [ ] I have updated the task(s) status on Linear
- [ ] All new media is optimized (images, gifs, videos)

### Browser support

My code works in the following browsers:

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

2024-06-20 12:58 UTC, kimkwanka commented
💯

2024-06-20 13:12 UTC, kimkwanka requested changes

2024-06-20 14:05 UTC, diogomateus commented on src/lib/components/modal/index.ts
> +  footer?: (onClose: () => void) => React.ReactNode;
Oh, good question! You can use either of the ways of closing the modal but using this one makes it have a smoother disappear animation similar to closing using. 

You can see this on the stories:
https://github.com/getPopsure/dirty-swan/assets/4015038/d7767bb6-0e4f-4ecb-9a73-8112ad3d526d

2024-06-20 14:32 UTC, diogomateus commented on src/lib/components/modal/index.ts
> +  footer?: (onClose: () => void) => React.ReactNode;
**Update:** Decided to fix the root of the issue and fix the closing animation, you can check my new commit with this udpate 🎉

2024-06-21 08:05 UTC, kimkwanka approved these changes

2024-06-21 10:05 UTC, merged